Check email in breaches module
osint-dev-team/osint-framework pull request #56
Opened 2020-08-21 06:45 UTC by Cravtos

There are no tests of many synchronous requests because the site will give a long timeout.

Think I will later add module doing the same thing, but using haveibeenpwned.com API. This module is kind of free but slow analog.

2020-08-27 17:04 UTC, manmolecular requested changes
Добавил ещё немного замечаний. Сейчас ночь, и надеюсь, что я ничего критичного не упустил, и ничего лишнего не ляпнул 😄 

Если что - пиши

2020-08-27 17:04 UTC, manmolecular commented on src/scripts/osint/email_breach/test_module.py
> +            raise SkipTest("Server respond with 429 (Too many requests)")
Т.к. этот кусок кода повторяется трижды, его лучше вынести в отдельную функцию:
```python3
def check_response_msg(message: str = "") -> None:
    """
    Check that response message is valid and applicable
    :param message: message of the response
    :return: None
    """
    if "429" in message:
        raise SkipTest("Server respond with 429 (Too many requests)")
```

А затем:
```python3
    def test_request(self) -> None:
        """
        Test email breach on johndoe@gmail.com.
        :return: None
        """
        response = self.runner.run(email="johndoe@gmail.com")
        check_response_msg(response.get("message"))
        ...
```
Или что-то типа того

2020-08-28 14:13 UTC, Cravtos commented
Fixed everything in 6d8cd91

2020-08-28 14:17 UTC, Cravtos commented on src/scripts/osint/email_breach/module.py
> +            if resp.status_code != 200:
Этот if повторяется в коде дважды. Стоит ли вынести его в отдельную фунцию и как, если стоит? (проблема в том, что в этом отрывке происходит возврат значения)

2020-08-31 06:21 UTC, manmolecular commented on src/scripts/osint/email_breach/module.py
> +            if resp.status_code != 200:
Можно было бы сделать простецкую лямбда-функцию на один аргумент:
```python3
    wrong_status = lambda status_code: ScriptResponse.error(
        message=f"Can't look up email in breaches. Server response: {status_code}."
    )
```
И вызывать как wrong_status(...), но это плохой паттерн.

Лучше просто использовать как есть, с проверкой и возвратом статуса, без отдельных функций в данном случае.

2020-08-31 06:25 UTC, manmolecular approved these changes
👍

2020-08-31 06:26 UTC, merged